[features]
seeds = false
skip-lint = false
[programs.localnet]
insurance = "DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix"
strategy = "5xFECAW3QY9nwfFSHhLAatHKZxcLv1ZtrMJEMs18rFik"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # implicitly also clones PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT