/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";
import * as beetSolana from "@metaplex-foundation/beet-solana";

/**
 * Arguments used to create {@link ClaimVoteAccount}
 * @category Accounts
 * @category generated
 */
export type ClaimVoteAccountArgs = {
  bump: number;
  voteAmount: beet.bignum;
  votedFor: boolean;
};

export const claimVoteAccountDiscriminator = [
  219, 43, 6, 164, 162, 169, 179, 96,
];
/**
 * Holds the data for the {@link ClaimVoteAccount} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class ClaimVoteAccount implements ClaimVoteAccountArgs {
  private constructor(
    readonly bump: number,
    readonly voteAmount: beet.bignum,
    readonly votedFor: boolean
  ) {}

  /**
   * Creates a {@link ClaimVoteAccount} instance from the provided args.
   */
  static fromArgs(args: ClaimVoteAccountArgs) {
    return new ClaimVoteAccount(args.bump, args.voteAmount, args.votedFor);
  }

  /**
   * Deserializes the {@link ClaimVoteAccount} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [ClaimVoteAccount, number] {
    return ClaimVoteAccount.deserialize(accountInfo.data, offset);
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link ClaimVoteAccount} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<ClaimVoteAccount> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    );
    if (accountInfo == null) {
      throw new Error(`Unable to find ClaimVoteAccount account at ${address}`);
    }
    return ClaimVoteAccount.fromAccountInfo(accountInfo, 0)[0];
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      "DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix"
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, claimVoteAccountBeet);
  }

  /**
   * Deserializes the {@link ClaimVoteAccount} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [ClaimVoteAccount, number] {
    return claimVoteAccountBeet.deserialize(buf, offset);
  }

  /**
   * Serializes the {@link ClaimVoteAccount} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return claimVoteAccountBeet.serialize({
      accountDiscriminator: claimVoteAccountDiscriminator,
      ...this,
    });
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link ClaimVoteAccount}
   */
  static get byteSize() {
    return claimVoteAccountBeet.byteSize;
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link ClaimVoteAccount} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      ClaimVoteAccount.byteSize,
      commitment
    );
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link ClaimVoteAccount} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === ClaimVoteAccount.byteSize;
  }

  /**
   * Returns a readable version of {@link ClaimVoteAccount} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      voteAmount: (() => {
        const x = <{ toNumber: () => number }>this.voteAmount;
        if (typeof x.toNumber === "function") {
          try {
            return x.toNumber();
          } catch (_) {
            return x;
          }
        }
        return x;
      })(),
      votedFor: this.votedFor,
    };
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const claimVoteAccountBeet = new beet.BeetStruct<
  ClaimVoteAccount,
  ClaimVoteAccountArgs & {
    accountDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["accountDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["bump", beet.u8],
    ["voteAmount", beet.u64],
    ["votedFor", beet.bool],
  ],
  ClaimVoteAccount.fromArgs,
  "ClaimVoteAccount"
);
