/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category AcceptReinsuranceProposal
 * @category generated
 */
export const acceptReinsuranceProposalStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */;
}>(
  [["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)]],
  "AcceptReinsuranceProposalInstructionArgs"
);
/**
 * Accounts required by the _acceptReinsuranceProposal_ instruction
 *
 * @property [**signer**] insuranceCreator
 * @property [_writable_] insurance
 * @property [_writable_] lp
 * @property [_writable_] proposal
 * @category Instructions
 * @category AcceptReinsuranceProposal
 * @category generated
 */
export type AcceptReinsuranceProposalInstructionAccounts = {
  insuranceCreator: web3.PublicKey;
  insurance: web3.PublicKey;
  lp: web3.PublicKey;
  proposal: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const acceptReinsuranceProposalInstructionDiscriminator = [
  112, 226, 252, 56, 81, 135, 97, 197,
];

/**
 * Creates a _AcceptReinsuranceProposal_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category AcceptReinsuranceProposal
 * @category generated
 */
export function createAcceptReinsuranceProposalInstruction(
  accounts: AcceptReinsuranceProposalInstructionAccounts,
  programId = new web3.PublicKey("DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix")
) {
  const [data] = acceptReinsuranceProposalStruct.serialize({
    instructionDiscriminator: acceptReinsuranceProposalInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.insuranceCreator,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.insurance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lp,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
