/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from "@solana/spl-token";
import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category AddSecurity
 * @category generated
 */
export type AddSecurityInstructionArgs = {
  transferAmount: beet.bignum;
};
/**
 * @category Instructions
 * @category AddSecurity
 * @category generated
 */
export const addSecurityStruct = new beet.BeetArgsStruct<
  AddSecurityInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["transferAmount", beet.u64],
  ],
  "AddSecurityInstructionArgs"
);
/**
 * Accounts required by the _addSecurity_ instruction
 *
 * @property [_writable_, **signer**] securityAddr
 * @property [_writable_] lp
 * @property [_writable_] securityAddrUsdcAcc
 * @property [_writable_] securityAdderTokenAddr
 * @property [_writable_] lpUsdcAccount
 * @property [_writable_] securityMint
 * @property [] tokenisedMint
 * @property [] usdcMint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category AddSecurity
 * @category generated
 */
export type AddSecurityInstructionAccounts = {
  securityAddr: web3.PublicKey;
  lp: web3.PublicKey;
  securityAddrUsdcAcc: web3.PublicKey;
  securityAdderTokenAddr: web3.PublicKey;
  lpUsdcAccount: web3.PublicKey;
  securityMint: web3.PublicKey;
  tokenisedMint: web3.PublicKey;
  usdcMint: web3.PublicKey;
  tokenProgram?: web3.PublicKey;
  associatedTokenProgram: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const addSecurityInstructionDiscriminator = [
  168, 178, 53, 168, 70, 125, 18, 5,
];

/**
 * Creates a _AddSecurity_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddSecurity
 * @category generated
 */
export function createAddSecurityInstruction(
  accounts: AddSecurityInstructionAccounts,
  args: AddSecurityInstructionArgs,
  programId = new web3.PublicKey("DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix")
) {
  const [data] = addSecurityStruct.serialize({
    instructionDiscriminator: addSecurityInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.securityAddr,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.lp,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.securityAddrUsdcAcc,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.securityAdderTokenAddr,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lpUsdcAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.securityMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenisedMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.usdcMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
