/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category BlockStrategy
 * @category generated
 */
export const blockStrategyStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'BlockStrategyInstructionArgs'
)
/**
 * Accounts required by the _blockStrategy_ instruction
 *
 * @property [**signer**] authorisedAddress
 * @property [_writable_] proposedStrategy
 * @category Instructions
 * @category BlockStrategy
 * @category generated
 */
export type BlockStrategyInstructionAccounts = {
  authorisedAddress: web3.PublicKey
  proposedStrategy: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const blockStrategyInstructionDiscriminator = [
  219, 180, 126, 94, 81, 115, 184, 36,
]

/**
 * Creates a _BlockStrategy_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category BlockStrategy
 * @category generated
 */
export function createBlockStrategyInstruction(
  accounts: BlockStrategyInstructionAccounts,
  programId = new web3.PublicKey('DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix')
) {
  const [data] = blockStrategyStruct.serialize({
    instructionDiscriminator: blockStrategyInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.authorisedAddress,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.proposedStrategy,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
