/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ProposeStrategy
 * @category generated
 */
export type ProposeStrategyInstructionArgs = {
  strategyId: string
  streamPayment: beet.bignum
  streamEvery: beet.bignum
  numberOfStreams: beet.bignum
}
/**
 * @category Instructions
 * @category ProposeStrategy
 * @category generated
 */
export const proposeStrategyStruct = new beet.FixableBeetArgsStruct<
  ProposeStrategyInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['strategyId', beet.utf8String],
    ['streamPayment', beet.u64],
    ['streamEvery', beet.u64],
    ['numberOfStreams', beet.u64],
  ],
  'ProposeStrategyInstructionArgs'
)
/**
 * Accounts required by the _proposeStrategy_ instruction
 *
 * @property [_writable_, **signer**] strategyProposer
 * @property [] premiumVault
 * @property [_writable_] proposedStrategy
 * @property [] strategyProgram
 * @category Instructions
 * @category ProposeStrategy
 * @category generated
 */
export type ProposeStrategyInstructionAccounts = {
  strategyProposer: web3.PublicKey
  premiumVault: web3.PublicKey
  proposedStrategy: web3.PublicKey
  strategyProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const proposeStrategyInstructionDiscriminator = [
  235, 195, 102, 215, 166, 202, 202, 135,
]

/**
 * Creates a _ProposeStrategy_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ProposeStrategy
 * @category generated
 */
export function createProposeStrategyInstruction(
  accounts: ProposeStrategyInstructionAccounts,
  args: ProposeStrategyInstructionArgs,
  programId = new web3.PublicKey('DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix')
) {
  const [data] = proposeStrategyStruct.serialize({
    instructionDiscriminator: proposeStrategyInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.strategyProposer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.premiumVault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposedStrategy,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.strategyProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
