/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RefundSecurity
 * @category generated
 */
export type RefundSecurityInstructionArgs = {
  refundAmount: beet.bignum
  securityRefundAmount: beet.bignum
}
/**
 * @category Instructions
 * @category RefundSecurity
 * @category generated
 */
export const refundSecurityStruct = new beet.BeetArgsStruct<
  RefundSecurityInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['refundAmount', beet.u64],
    ['securityRefundAmount', beet.u64],
  ],
  'RefundSecurityInstructionArgs'
)
/**
 * Accounts required by the _refundSecurity_ instruction
 *
 * @property [**signer**] securityAddr
 * @property [_writable_] lp
 * @property [_writable_] securityAddrUsdcAcc
 * @property [_writable_] securityAdderTokenAddr
 * @property [_writable_] lpUsdcAccount
 * @property [_writable_] securityMint
 * @property [] tokenisedMint
 * @property [] usdcMint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category RefundSecurity
 * @category generated
 */
export type RefundSecurityInstructionAccounts = {
  securityAddr: web3.PublicKey
  lp: web3.PublicKey
  securityAddrUsdcAcc: web3.PublicKey
  securityAdderTokenAddr: web3.PublicKey
  lpUsdcAccount: web3.PublicKey
  securityMint: web3.PublicKey
  tokenisedMint: web3.PublicKey
  usdcMint: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const refundSecurityInstructionDiscriminator = [
  82, 132, 101, 168, 19, 221, 159, 152,
]

/**
 * Creates a _RefundSecurity_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RefundSecurity
 * @category generated
 */
export function createRefundSecurityInstruction(
  accounts: RefundSecurityInstructionAccounts,
  args: RefundSecurityInstructionArgs,
  programId = new web3.PublicKey('DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix')
) {
  const [data] = refundSecurityStruct.serialize({
    instructionDiscriminator: refundSecurityInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.securityAddr,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.lp,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.securityAddrUsdcAcc,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.securityAdderTokenAddr,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lpUsdcAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.securityMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenisedMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.usdcMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
