/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RegisterInsurer
 * @category generated
 */
export type RegisterInsurerInstructionArgs = {
  verifyingDocuments: string
}
/**
 * @category Instructions
 * @category RegisterInsurer
 * @category generated
 */
export const registerInsurerStruct = new beet.FixableBeetArgsStruct<
  RegisterInsurerInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['verifyingDocuments', beet.utf8String],
  ],
  'RegisterInsurerInstructionArgs'
)
/**
 * Accounts required by the _registerInsurer_ instruction
 *
 * @property [_writable_, **signer**] insuranceCreator
 * @property [_writable_] insurer
 * @category Instructions
 * @category RegisterInsurer
 * @category generated
 */
export type RegisterInsurerInstructionAccounts = {
  insuranceCreator: web3.PublicKey
  insurer: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const registerInsurerInstructionDiscriminator = [
  183, 169, 28, 151, 61, 123, 29, 55,
]

/**
 * Creates a _RegisterInsurer_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RegisterInsurer
 * @category generated
 */
export function createRegisterInsurerInstruction(
  accounts: RegisterInsurerInstructionAccounts,
  args: RegisterInsurerInstructionArgs,
  programId = new web3.PublicKey('DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix')
) {
  const [data] = registerInsurerStruct.serialize({
    instructionDiscriminator: registerInsurerInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.insuranceCreator,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.insurer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
