/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category TransferToSecurity
 * @category generated
 */
export const transferToSecurityStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'TransferToSecurityInstructionArgs'
)
/**
 * Accounts required by the _transferToSecurity_ instruction
 *
 * @property [**signer**] transferrer
 * @property [] lp
 * @property [] proposal
 * @property [_writable_] lpUsdcAccount
 * @property [] premiumVault
 * @property [_writable_] premiumVaultTokenAccount
 * @property [] usdcMint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category TransferToSecurity
 * @category generated
 */
export type TransferToSecurityInstructionAccounts = {
  transferrer: web3.PublicKey
  lp: web3.PublicKey
  proposal: web3.PublicKey
  lpUsdcAccount: web3.PublicKey
  premiumVault: web3.PublicKey
  premiumVaultTokenAccount: web3.PublicKey
  usdcMint: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const transferToSecurityInstructionDiscriminator = [
  252, 170, 205, 125, 150, 49, 210, 132,
]

/**
 * Creates a _TransferToSecurity_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category TransferToSecurity
 * @category generated
 */
export function createTransferToSecurityInstruction(
  accounts: TransferToSecurityInstructionAccounts,
  programId = new web3.PublicKey('DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix')
) {
  const [data] = transferToSecurityStruct.serialize({
    instructionDiscriminator: transferToSecurityInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.transferrer,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.lp,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.lpUsdcAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.premiumVault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.premiumVaultTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.usdcMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
