/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link ReInsuranceVoteAccount}
 * @category Accounts
 * @category generated
 */
export type ReInsuranceVoteAccountArgs = {
  bump: number
}

export const reInsuranceVoteAccountDiscriminator = [
  101, 100, 201, 18, 24, 242, 186, 90,
]
/**
 * Holds the data for the {@link ReInsuranceVoteAccount} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class ReInsuranceVoteAccount implements ReInsuranceVoteAccountArgs {
  private constructor(readonly bump: number) {}

  /**
   * Creates a {@link ReInsuranceVoteAccount} instance from the provided args.
   */
  static fromArgs(args: ReInsuranceVoteAccountArgs) {
    return new ReInsuranceVoteAccount(args.bump)
  }

  /**
   * Deserializes the {@link ReInsuranceVoteAccount} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [ReInsuranceVoteAccount, number] {
    return ReInsuranceVoteAccount.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link ReInsuranceVoteAccount} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<ReInsuranceVoteAccount> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find ReInsuranceVoteAccount account at ${address}`
      )
    }
    return ReInsuranceVoteAccount.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(
      programId,
      reInsuranceVoteAccountBeet
    )
  }

  /**
   * Deserializes the {@link ReInsuranceVoteAccount} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(
    buf: Buffer,
    offset = 0
  ): [ReInsuranceVoteAccount, number] {
    return reInsuranceVoteAccountBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link ReInsuranceVoteAccount} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return reInsuranceVoteAccountBeet.serialize({
      accountDiscriminator: reInsuranceVoteAccountDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link ReInsuranceVoteAccount}
   */
  static get byteSize() {
    return reInsuranceVoteAccountBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link ReInsuranceVoteAccount} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      ReInsuranceVoteAccount.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link ReInsuranceVoteAccount} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === ReInsuranceVoteAccount.byteSize
  }

  /**
   * Returns a readable version of {@link ReInsuranceVoteAccount} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const reInsuranceVoteAccountBeet = new beet.BeetStruct<
  ReInsuranceVoteAccount,
  ReInsuranceVoteAccountArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
  ],
  ReInsuranceVoteAccount.fromArgs,
  'ReInsuranceVoteAccount'
)
