/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link StrategyVoteAccount}
 * @category Accounts
 * @category generated
 */
export type StrategyVoteAccountArgs = {
  bump: number
}

export const strategyVoteAccountDiscriminator = [
  36, 142, 164, 124, 1, 247, 76, 208,
]
/**
 * Holds the data for the {@link StrategyVoteAccount} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class StrategyVoteAccount implements StrategyVoteAccountArgs {
  private constructor(readonly bump: number) {}

  /**
   * Creates a {@link StrategyVoteAccount} instance from the provided args.
   */
  static fromArgs(args: StrategyVoteAccountArgs) {
    return new StrategyVoteAccount(args.bump)
  }

  /**
   * Deserializes the {@link StrategyVoteAccount} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [StrategyVoteAccount, number] {
    return StrategyVoteAccount.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link StrategyVoteAccount} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<StrategyVoteAccount> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find StrategyVoteAccount account at ${address}`
      )
    }
    return StrategyVoteAccount.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'DajsLYULhHh3SVSDHsCCvnuHD8JeXgVf5mjfnQWpwzix'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, strategyVoteAccountBeet)
  }

  /**
   * Deserializes the {@link StrategyVoteAccount} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [StrategyVoteAccount, number] {
    return strategyVoteAccountBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link StrategyVoteAccount} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return strategyVoteAccountBeet.serialize({
      accountDiscriminator: strategyVoteAccountDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link StrategyVoteAccount}
   */
  static get byteSize() {
    return strategyVoteAccountBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link StrategyVoteAccount} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      StrategyVoteAccount.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link StrategyVoteAccount} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === StrategyVoteAccount.byteSize
  }

  /**
   * Returns a readable version of {@link StrategyVoteAccount} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const strategyVoteAccountBeet = new beet.BeetStruct<
  StrategyVoteAccount,
  StrategyVoteAccountArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
  ],
  StrategyVoteAccount.fromArgs,
  'StrategyVoteAccount'
)
